Repository FriendsOfTYPO3/introduction, pull requests merged in 2021-10, with the labels that each got.

#54 [FEATURE] Update Bootstrap Package and add new content elements
  Initialisation/data.xml
  Initialisation/data.xml.files/03be0abeb7c820cdc7040651572a29fae0b7be77
  Initialisation/data.xml.files/0b21b119be185e4feb8eaa7c48afa5664e632b42
  Initialisation/data.xml.files/1447c3e242b0907ef39d09d73e597729d5ef47b5
  Initialisation/data.xml.files/20b01df90bf873c09107d4e0bec7f10c431882e4
  Initialisation/data.xml.files/2e4596c4ec0e1566584c60547cb2b87d883cd3ef
  Initialisation/data.xml.files/395e3020af639ef7c3b3311f169f4b78f4f77e97
  Initialisation/data.xml.files/8f93c3bf16ea796c24fe15d817f25bd48cddfe7d
  Initialisation/data.xml.files/99625289176c1a8d8994c040c9339ac42b02d31e
  Initialisation/data.xml.files/9b7b0a9a0cac5b37a6d8d2cbf6337025d92c6389
  Initialisation/data.xml.files/ce6ba85a7f45f635ac88e8f6da33f1cccece1e2b
  Initialisation/data.xml.files/fd7ac3fa6228de733aef90d25521c2667242ff7f
  composer.json
Labels: enhancement

#60 [TASK] Fix Xdebug configuration
  .vscode/launch.json
Labels: maintenance

#61 [TASK] Fix docs configuration and links
  .github/workflows/release.yml
  Documentation/Maintenance.rst
  Documentation/Settings.cfg
Labels: maintenance

#62 [BUGFIX] Error handling configuration
  Classes/EventListener/AfterExtensionSiteFilesHaveBeenImportedEventListener.php
  Configuration/Services.yaml
  Initialisation/Site/introduction/config.yaml
  composer.json
  ext_emconf.php
  ext_localconf.php
Labels: bug

#63 [BUGFIX] Error handling configuration
  Classes/EventListener/AfterExtensionSiteFilesHaveBeenImportedEventListener.php
  composer.json
  ext_emconf.php
Labels: bug

#64 [BUGFIX] Cast page uid for error handler to int
  Classes/EventListener/AfterExtensionSiteFilesHaveBeenImportedEventListener.php
Labels: bug

#55 [FEATURE] Update to TYPO3 v11
  Initialisation/data.xml
  Initialisation/data.xml.files/ce479424071718eaed7c8536432b83bc71249631
  composer.json
Labels: enhancement

#65 [BUGFIX] Dependencies in ext_emconf.php
  ext_emconf.php
Labels: bug

#66 [TASK] Allow PHP 8 and higher
  composer.json
Labels: maintenance
