Repository FriendsOfTYPO3/introduction, pull requests merged in 2023-04, with the labels that each got.

#86 [TASK] Add typo3/cms-beuser for maintenance
  composer.json
Labels: maintenance

#87 [TASK] Avoid circular dependencies for user groups
  Initialisation/data.xml
Labels: maintenance

#88 [FEATURE] Update Bootstrap Package to v13
  composer.json
Labels: enhancement

#89 [TASK] Update actions
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: maintenance

#90 [TASK] Require typo3/cms-beuser
  composer.json
  ext_emconf.php
Labels: maintenance

#91 [TASK] Simplify workflows by using choices
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: maintenance

#85 [FEATURE] Update to TYPO3 v12
  .ddev/commands/host/reset
  .ddev/config.yaml
  .gitattributes
  .gitignore
  Documentation/Maintenance.rst
  Initialisation/data.xml
  README.md
  composer.json
  ext_emconf.php
Labels: enhancement

#81 [TASK] Make clear these introductions are for contribution
  Documentation/Maintenance.rst
Labels: maintenance

#93 [BUGFIX] Fix translations and wrong language assignment
  Initialisation/Site/introduction/config.yaml
  Initialisation/data.xml
Labels: bug
