Repository FriendsOfTYPO3/introduction, pull requests merged in 2023-06, with the labels that each got.

#94 [BUGFIX] Correct target PID of redirect form finisher
  Initialisation/data.xml
Labels: bug

#96 [BUGFIX] remove empty paragraph tags
  Initialisation/data.xml
Labels: bug

#97 [DOCS] Rewrite DDEV maintenance
  Documentation/Maintenance.rst
Labels: documentation

#98 [DOCS] Fix links
  Build/render-docs.bat
  Build/render-docs.sh
  Build/render-docs.yaml
  Documentation/Index.rst
  Documentation/Installation.rst
  Documentation/Maintenance.rst
  Documentation/Settings.cfg
Labels: documentation

#99 [TASK] Move Xdebug config to launch.json
  .ddev/php/xdebug.ini
  .vscode/launch.json
Labels: maintenance

#100 [BUGFIX] Add Autocomplete to Example Form
  Resources/Private/Forms/introduction-contact-form.form.yaml
Labels: bug

#101 [TASK] Update GitHub URL of TYPO3 core
  Initialisation/data.xml
Labels: maintenance
