Repository FriendsOfTYPO3/introduction, pull requests merged in 2023-07, with the labels that each got.

#103 [TASK] Avoid using inline styles in embedded SVG
  Initialisation/Files/images/introduction-package-inverted.svg
  Initialisation/Files/images/introduction-package.svg
  Initialisation/data.xml.files/39cd9505dce74d453d7b1270b03b0e60b071ddaf
Labels: maintenance

#106 [TASK] Add acceptance tests
  .ddev/commands/host/run-tests
  .ddev/docker-compose.chrome.yaml.template
  .gitattributes
  .github/workflows/tests.yml
  .gitignore
  Tests/Acceptance.suite.yml
  Tests/Acceptance/Frontend/ContentExamplesPageCest.php
  Tests/Acceptance/Frontend/CustomizePageCest.php
  Tests/Acceptance/Frontend/FeaturesPageCest.php
  Tests/Acceptance/Frontend/HomePageCest.php
  Tests/Acceptance/Frontend/PagesPageCest.php
  Tests/Support/AcceptanceTester.php
  Tests/Support/Data/.gitignore
  Tests/Support/Helper/MenuTestTrait.php
  Tests/Support/_generated/.gitignore
  Tests/_output/.gitignore
  codeception.yml
  composer.json
Labels: maintenance

#107 [TASK] Streamline dependencies
  composer.json
Labels: maintenance

#108 [TASK] Test various PHP and dev versions
  .github/workflows/tests.yml
Labels: maintenance

#109 [DOCS] Update TER description
  ext_emconf.php
Labels: documentation

#110 [DOCS] Add description to run tests locally
  Documentation/Maintenance.rst
Labels: documentation

#111 [FEATURE] Update Bootstrap Package to v14
  composer.json
Labels: enhancement
